name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    env:
      TESTPIG_API_KEY: ${{ secrets.TESTPIG_API_KEY}}
      TESTPIG_DEBUG_LOGS: true
      TESTPIG_PROJECT_ID: ee47c
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci

      # - name: Setup Chrome
      #   uses: browser-actions/setup-chrome@v1
      #   with:
      #     chrome-version: '131'
  
      # - uses: nanasess/setup-chromedriver@v2
      #   with:
      #     chromedriver-version: '131.0.6778.87'

      - name: Install Playwright browsers
        run: |
          npx playwright install-deps 
          npx playwright install

      - name: Build packages
        run: npx lerna run build

      # - name: Run tests for webdriverio tests
      #   run: npx lerna run test --scope=@testpig/webdriverio-tests

      - name: Run tests for core package
        run: |
          npx lerna run test --scope=@testpig/core --scope=@testpig/shared

      - name: Run tests for shared package
        run: npx lerna run test --scope=@testpig/shared

      - name: Run tests for cypress tests
        run: npx lerna run test --scope=@testpig/cypress-tests

      - name: Run tests for jest tests
        run: npx lerna run test --scope=@testpig/jest-tests

      - name: Run tests for mocha tests
        run: npx lerna run test --scope=@testpig/mocha-tests

      - name: Run tests for playwright tests
        run: npx lerna run test --scope=@testpig/playwright-tests

      - name: Run tests for vitest tests
        run: npx lerna run test --scope=@testpig/vitest-tests
