name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    env:
      TESTPIG_API_KEY: ${{ secrets.TESTPIG_API_KEY}}
      TESTPIG_DEBUG_LOGS: true
      TESTPIG_PROJECT_ID: ee47c
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci

      # - name: Setup Chrome
      #   uses: browser-actions/setup-chrome@v1
      #   with:
      #     chrome-version: '131'
  
      # - uses: nanasess/setup-chromedriver@v2
      #   with:
      #     chromedriver-version: '131.0.6778.87'

      - name: Install Playwright browsers
        run: |
          npx playwright install-deps 
          npx playwright install

      - name: Build packages
        run: npx lerna run build

      - name: Create test results directory
        run: mkdir -p test-results

      # - name: Run tests for webdriverio tests
      #   run: npx lerna run test --scope=@testpig/webdriverio-tests

      - name: Run tests for core package
        run: |
          npx lerna run test --scope=@testpig/core --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-core.log || true

      - name: Run tests for shared package
        run: npx lerna run test --scope=@testpig/shared --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-shared.log || true

      - name: Run tests for cypress tests
        run: npx lerna run test --scope=@testpig/cypress-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-cypress.log || true

      - name: Run tests for jest tests
        run: npx lerna run test --scope=@testpig/jest-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-jest.log || true

      - name: Run tests for mocha tests
        run: npx lerna run test --scope=@testpig/mocha-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-mocha.log || true

      - name: Run tests for playwright tests
        run: npx lerna run test --scope=@testpig/playwright-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-playwright.log || true

      - name: Run tests for vitest tests
        run: npx lerna run test --scope=@testpig/vitest-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-vitest.log || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node-version }}
          path: test-results

  test-git-env-cli:
    # Test the new testpig-git-env CLI using local build
    # (package not published yet, so we test directly from dist/)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npx lerna run build --scope=@testpig/shared

      - name: Test CLI Help
        run: |
          echo "=== Testing CLI Help ==="
          node packages/shared/dist/bin/git-env.js --help

      - name: Test CLI Basic Output
        run: |
          echo "=== Testing CLI Basic Output ==="
          node packages/shared/dist/bin/git-env.js

      - name: Test CLI JSON Output
        run: |
          echo "=== Testing CLI JSON Output ==="
          node packages/shared/dist/bin/git-env.js --json

      - name: Test CLI Verbose Mode
        run: |
          echo "=== Testing CLI Verbose Mode ==="
          node packages/shared/dist/bin/git-env.js --verbose --json

      - name: Test GitHub Actions Detection
        run: |
          echo "=== Testing GitHub Actions Detection ==="
          echo "Expected GitHub Actions to be detected:"
          echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          echo ""
          echo "CLI Output:"
          node packages/shared/dist/bin/git-env.js --verbose --json

      - name: Test TestPig Environment Variable Overrides
        run: |
          echo "=== Testing TestPig Overrides ==="
          export TESTPIG_GIT_BRANCH="test-override-branch"
          export TESTPIG_GIT_AUTHOR="Test Override User"
          export TESTPIG_GIT_EMAIL="test@example.com"
          export TESTPIG_CI_PROVIDER="test-provider"
          echo "Set overrides:"
          echo "TESTPIG_GIT_BRANCH=$TESTPIG_GIT_BRANCH"
          echo "TESTPIG_GIT_AUTHOR=$TESTPIG_GIT_AUTHOR"
          echo "TESTPIG_GIT_EMAIL=$TESTPIG_GIT_EMAIL"
          echo "TESTPIG_CI_PROVIDER=$TESTPIG_CI_PROVIDER"
          echo ""
          echo "CLI Output with overrides:"
          node packages/shared/dist/bin/git-env.js --json

      - name: Test Docker Environment Variables
        run: |
          echo "=== Testing Docker Environment Variables ==="
          echo "Environment variables that would be passed to Docker:"
          node packages/shared/dist/bin/git-env.js
          echo ""
          echo "Formatted for easy reading:"
          node packages/shared/dist/bin/git-env.js | tr ' ' '\n'

      - name: Test Docker Command Simulation
        run: |
          echo "=== Simulating Docker Command ==="
          echo "This is how the Docker command would look:"
          echo "docker run --rm \$(node packages/shared/dist/bin/git-env.js) my-test-image"
          echo ""
          echo "Which expands to:"
          echo "docker run --rm $(node packages/shared/dist/bin/git-env.js) my-test-image"

      - name: Validate CLI Output Format
        run: |
          echo "=== Validating CLI Output Format ==="
          # Test that basic output contains expected environment variables
          output=$(node packages/shared/dist/bin/git-env.js)
          echo "Raw output: $output"
          
          # Check for required environment variables
          if [[ $output == *"TESTPIG_GIT_BRANCH="* ]]; then
            echo "✅ TESTPIG_GIT_BRANCH found"
          else
            echo "❌ TESTPIG_GIT_BRANCH missing" && exit 1
          fi
          
          if [[ $output == *"TESTPIG_GIT_COMMIT="* ]]; then
            echo "✅ TESTPIG_GIT_COMMIT found"
          else
            echo "❌ TESTPIG_GIT_COMMIT missing" && exit 1
          fi
          
          if [[ $output == *"TESTPIG_GIT_AUTHOR="* ]]; then
            echo "✅ TESTPIG_GIT_AUTHOR found"
          else
            echo "❌ TESTPIG_GIT_AUTHOR missing" && exit 1
          fi
          
          if [[ $output == *"TESTPIG_CI_PROVIDER="* ]]; then
            echo "✅ TESTPIG_CI_PROVIDER found"
          else
            echo "❌ TESTPIG_CI_PROVIDER missing" && exit 1
          fi
          
          echo "✅ All required environment variables present"

      - name: Test JSON Output Validation
        run: |
          echo "=== Validating JSON Output ==="
          # Test that JSON output is valid and contains expected fields
          json_output=$(node packages/shared/dist/bin/git-env.js --json)
          echo "JSON output: $json_output"
          
          # Validate JSON is parseable
          echo "$json_output" | jq . > /dev/null
          echo "✅ JSON is valid"
          
          # Check required fields
          branch=$(echo "$json_output" | jq -r '.branch')
          commit=$(echo "$json_output" | jq -r '.commit')
          author=$(echo "$json_output" | jq -r '.author')
          provider=$(echo "$json_output" | jq -r '.provider')
          isCI=$(echo "$json_output" | jq -r '.isCI')
          
          echo "Extracted values:"
          echo "- branch: $branch"
          echo "- commit: $commit"
          echo "- author: $author"
          echo "- provider: $provider"
          echo "- isCI: $isCI"
          
          # Validate values are not "unknown" or "null"
          if [[ "$branch" != "unknown" && "$branch" != "null" ]]; then
            echo "✅ Branch detected correctly"
          else
            echo "❌ Branch detection failed" && exit 1
          fi
          
          if [[ "$commit" != "unknown" && "$commit" != "null" ]]; then
            echo "✅ Commit detected correctly"
          else
            echo "❌ Commit detection failed" && exit 1
          fi
          
          if [[ "$isCI" == "true" ]]; then
            echo "✅ CI environment detected correctly"
          else
            echo "❌ CI environment detection failed" && exit 1
          fi
          
          echo "✅ All JSON fields validated successfully"
