name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    env:
      TESTPIG_API_KEY: ${{ secrets.TESTPIG_API_KEY}}
      TESTPIG_DEBUG_LOGS: true
      TESTPIG_PROJECT_ID: ee47c
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci

      # - name: Setup Chrome
      #   uses: browser-actions/setup-chrome@v1
      #   with:
      #     chrome-version: '131'
  
      # - uses: nanasess/setup-chromedriver@v2
      #   with:
      #     chromedriver-version: '131.0.6778.87'

      - name: Install Playwright browsers
        run: |
          npx playwright install-deps 
          npx playwright install

      - name: Build packages
        run: npx lerna run build

      - name: Create test results directory
        run: mkdir -p test-results

      # - name: Run tests for webdriverio tests
      #   run: npx lerna run test --scope=@testpig/webdriverio-tests

      - name: Run tests for core package
        run: |
          npx lerna run test --scope=@testpig/core --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-core.log || true

      - name: Run tests for shared package
        run: npx lerna run test --scope=@testpig/shared --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-shared.log || true

      - name: Run tests for cypress tests
        run: npx lerna run test --scope=@testpig/cypress-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-cypress.log || true

      - name: Run tests for jest tests
        run: npx lerna run test --scope=@testpig/jest-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-jest.log || true

      - name: Run tests for mocha tests
        run: npx lerna run test --scope=@testpig/mocha-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-mocha.log || true

      - name: Run tests for playwright tests
        run: npx lerna run test --scope=@testpig/playwright-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-playwright.log || true

      - name: Run tests for vitest tests
        run: npx lerna run test --scope=@testpig/vitest-tests --verbose 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > test-results/test-vitest.log || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node-version }}
          path: test-results
